# Test page

```{r}
library(tidyverse)
```


```{r}

data = read.csv("Data1001 Survey Responses.csv")


colnames(data) <- c("Timestamp","Gender","Age","Employment","ScreenTime","SleepTime","Devices","StudyTime","BedTime","Notes")


table(data$Devices)

# re-order devices
data$Devices <- factor(data$Devices , levels=c("1","2","3","4",">5"))

str(data)

fit = lm(data$SleepTime~ data$ScreenTime)
cor(data$ScreenTime, data$SleepTime)
summary(fit)

ggplot(data) +
  aes(x = ScreenTime, y = SleepTime) +
  labs(x = "Screen Time (hours)", y = "Sleep Time (hours)", title = "Screen Time & Sleep Time") +
  geom_point() +
  geom_smooth(method = "lm")
cor(data$ScreenTime, data$SleepTime)

fit = lm(Sl)


ggplot(data) +
  aes(x = Employment, y = ScreenTime) +
  labs(x = "Employment Type", y = "Average Screen Time (hours)", title = "Screen time & Employment Type") +
  geom_boxplot()

ggplot(data) +
  aes(x = Devices, y = ScreenTime) +
  labs(x = "Number of Devices used", y = "Average Screen time (hours)", title = "Screen time & Number of Devices used") +
  geom_boxplot()

ggplot(data) +
  aes(x = BedTime, y = ScreenTime) +
  labs(x = "Bed Time", y = "Average Screen Time (hours)", title = "Bed Time and Screen Time") +
  geom_col()

ggplot(data) +
  aes(x = Devices, fill = Notes) +
  geom_bar()


ggplot(data) +
  aes(x = Gender, y = ScreenTime) +
  labs(x = "Gender", y = "Screen Time (hours)", title = "Gender & Screen Time") +
  geom_boxplot()


ggplot(data) + 
  aes(x = Gender, fill = Devices) +
  geom_bar()

ggplot(data) +
  aes(x = Notes, fill = Gender) +
  geom_bar()


```

